allowBuilds:
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  sharp: false
  unrs-resolver: false
overrides:
  deepmerge-ts: 8.0.2
  effect: 3.22.2
  fast-uri: 3.1.8
  mysql2: 3.24.5
  qs: 6.16.0
