import { defineConfig } from "vitest/config";

export default defineConfig({
  resolve: {
    tsconfigPaths: true,
  },
  test: {
    environment: "node",
    include: ["tests/integration/**/*.test.ts"],
    setupFiles: ["tests/integration/setup.ts"],
    reporters: ["default", ["junit", { outputFile: "test-results/integration-junit.xml" }]],
    fileParallelism: false,
    maxWorkers: 1,
    testTimeout: 20_000,
    hookTimeout: 20_000,
    coverage: {
      provider: "v8",
      include: [
        "lib/access/**/*.ts",
        "lib/actions/activity.ts",
        "lib/actions/client.ts",
        "lib/actions/comment.ts",
        "lib/actions/define.ts",
        "lib/actions/deliverable.ts",
        "lib/actions/invoice.ts",
        "lib/actions/portal-actions.ts",
        "lib/actions/project.ts",
        "lib/actions/request.ts",
        "lib/actions/task.ts",
        "lib/actions/team.ts",
        "lib/actions/workspace.ts",
        "lib/invoice/**/*.ts",
      ],
      exclude: ["**/*.test.ts"],
      reporter: ["text", "lcov", "json-summary"],
      reportsDirectory: "coverage/integration",
      thresholds: {
        statements: 55,
        branches: 45,
        functions: 55,
        lines: 60,
        "lib/access/**/*.ts": {
          statements: 70,
          branches: 35,
          functions: 60,
          lines: 72,
        },
        "lib/actions/define.ts": {
          statements: 95,
          branches: 90,
          functions: 95,
          lines: 95,
        },
        "lib/actions/deliverable.ts": {
          statements: 65,
          branches: 65,
          functions: 45,
          lines: 70,
        },
        "lib/actions/invoice.ts": {
          statements: 58,
          branches: 48,
          functions: 85,
          lines: 68,
        },
        "lib/actions/portal-actions.ts": {
          statements: 50,
          branches: 30,
          functions: 45,
          lines: 52,
        },
        "lib/invoice/**/*.ts": {
          statements: 78,
          branches: 55,
          functions: 75,
          lines: 80,
        },
      },
    },
  },
});
